.pre-commit-config.yaml, pyproject.toml, pytket/phir/api.py, pytket/phir/phirgen.py, pytket/phir/place_and_route.py, pytket/phir/sharding/shard.py, requirements.txt, tests/e2e_test.py
To avoid breakage after merge of CQCL/phir#8.
=> Don't do strict validation for phirmodel, update angle and duration generation

pytket/phir/api.py, pytket/phir/place_and_route.py, tests/e2e_test.py, tests/test_api.py
allow full e2e use without specifying a machine object
=> Make machine argument optional

.github/dependabot.yml, README.md, docs/source/index.rst, pyproject.toml, pytket/phir/phirgen.py, requirements.txt
- docs: fix link to PHIR spec
- To sync with upstream change https://github.com/CQCL/phir/commit/41433c82fe6f2d609ecff7bc7f6b4df9276aa8bb
- build: update phir version, add classifiers
- ci: Add `dependabot.yml` for automatic dependency updates
=> docs/build/ci: fix link to PHIR spec; update `phir`, add `dependabot.yml`

pytket/phir/phirgen.py, pytket/phir/place_and_route.py, pytket/phir/placement.py, pytket/phir/sharding/shard.py, pytket/phir/sharding/shards2ops.py
We seem to have two different notions of layers, so I am renaming the previous `Layer` type to `ShardLayer` and introducing another `Layer` type to make the return type of `parse_shards_naive` concise.
Other suggestions welcome!
=> Rename `Layer` -> `ShardLayer`, and introduce another `Layer` type

.github/dependabot.yml
Learned from https://github.com/CQCL/phir/pull/17 and https://github.com/CQCL/phir/pull/18 that the prefix is redundant.
=> ci: Remove redundant deps from commit prefix

pyproject.toml, pytket/phir/cli.py
Will need to add optional dependency for pecos later, after https://github.com/PECOS-packages/PECOS/pull/20 is merged and a versioned package released.
=> feat: add `phirc` CLI driver and setuptools scm for auto versioning

pyproject.toml
Installation from PyPI currently fails with two errors:
```py
❯ phirc -v
Traceback (most recent call last):
File "/private/tmp/.venv/bin/phirc", line 5, in <module>
from pytket.phir.cli import main
File "/private/tmp/.venv/lib/python3.11/site-packages/pytket/phir/cli.py", line 14, in <module>
from pecos.engines.hybrid_engine import HybridEngine  # type:ignore [import-not-found]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pecos'
❯ pip install "quantum-pecos@git+https://github.com/PECOS-packages/PECOS.git@e2e-testing"
[...]
❯ phirc -v
Traceback (most recent call last):
File "/private/tmp/.venv/bin/phirc", line 5, in <module>
from pytket.phir.cli import main
File "/private/tmp/.venv/lib/python3.11/site-packages/pytket/phir/cli.py", line 23, in …
```
=> build: add missing dep, correct Python constraint

.pre-commit-config.yaml, README.md, pyproject.toml, requirements.txt
Also pin `networkx` as `projectq` downgrades it.
=> build: phirc also needs projectq, other cleanup

pytket/phir/phirgen.py, pytket/phir/sharding/sharder.py, tests/test_api.py, tests/test_parallel_tk2.py, tests/test_parallelization.py, tests/test_sharder.py
=> Add support for `CopyBits` op

pytket/phir/cli.py, pytket/phir/sharding/sharder.py, tests/data/qasm/classical_ordering.qasm, tests/test_sharder.py, tests/test_utils.py
-sharder now checks for WAW and WAR instead of just one
-fixed typo in cli.py (there is no args.tk, it should be args.tk_opt_level)
=> Issue 92 Classical Ordering

.pre-commit-config.yaml, pytket/phir/phirgen.py, requirements.txt, tests/test_phirgen.py
I need to confirm whether PECOS/PHIR supports the `POW` operation as [the spec](https://github.com/CQCL/phir/blob/main/spec.md#table-i---cop-assignment-arithmetic-comparison--bitwise-operations) doesn't list it.
=> fix(phirgen): pattern match on all possible regwise/bitwise ops

.pre-commit-config.yaml, pyproject.toml, pytket/phir/api.py, pytket/phir/cli.py, pytket/phir/phirgen.py, requirements.txt, tests/test_sharder.py, tests/test_utils.py
[`reburb`](https://github.com/dosisod/refurb) is like clippy for Python.
=> style: add refurb and apply its changes, upgrade wasmtime

README.md, pyproject.toml, pytket/phir/api.py, pytket/phir/cli.py, pytket/phir/machine.py, pytket/phir/qtm_machine.py, pytket/phir/rebasing/rebaser.py, requirements.txt, tests/e2e_test.py, tests/test_placement.py, tests/test_rebaser.py, tests/test_utils.py
And remove the `tket_optimization_level` argument to `pytket_to_phir()`. Add a `gateset` field to the `Machine` class and populate the `QtmMachine` instances with the current supported gatesets. Apply a standard rebase pass after decomposing boxes (i.e. optimization level 0).
Create a dataclass for machine timing data to get around ruff's (quite reasonable) complaint that there were too many arguments to `Machine.__init__()`.
=> Remove pytket-quantinuum dependency.

.pre-commit-config.yaml, pyproject.toml, pytket/phir/cli.py, pytket/phir/phirgen.py, requirements.txt, tests/data/qasm/cond_barrier.qasm, tests/test_parallelization.py, tests/test_phirgen.py, tests/test_utils.py
Closes https://github.com/CQCL/pytket-phir/issues/119
Requires https://github.com/CQCL/phir/pull/56 which I will release as phir v0.3.0
Needs support for barrier instructions in pecos / or a new pre-release with this change https://github.com/PECOS-packages/PECOS/commit/1c9e36598fddb18432d63cd59fb1f64b6367315b
=> fix(phirgen): emit barrier instructions as well

pytket/phir/phirgen.py, tests/test_phirgen.py
recursive call in classical op is now bitwise
tests still pass after removing type error at lines 150,151 in phirgen.py
Fixes #133
=> issue 133 bugfix for nested bitwise ops

pytket/phir/phirgen.py, requirements.txt, tests/data/phase.json, tests/test_phirgen.py, tests/test_wasm.py
We currently error out on (global) Phase, which is a problem as global phase is a harmless operation. I propose a no-op `mop` instruction `"Skip"` instead to handle this scenario.
Fixes #136
=> fix(phirgen): emit Skip mop instead of error on global phase

.pre-commit-config.yaml, pyproject.toml, pytket/phir/phirgen.py, requirements.txt, tests/data/qasm/sleep.qasm, tests/test_parallelization.py, tests/test_phirgen.py, tests/test_utils.py
Add support for QASM's `sleep` operation that gets converted by pytket into a barrier with `op.data` carrying the sleep information. We convert it into the existing PHIR `"Idle"` `"mop"`.
Also update several dependencies.
=> feat(phirgen): add support for Sleep/Idle mop

.pre-commit-config.yaml, pytket/phir/cli.py, pytket/phir/phirgen.py, requirements.txt, tests/test_phirgen.py, tests/test_sharder.py
Incorrectly added duration as strings in the last release. While improving the phir model validation in https://github.com/CQCL/phir/pull/66, discovered that the RHS to assign_cop was typed as a list of booleans instead of ints.
=> fix(phirgen): float not str for duration

pytket/phir/phirgen.py, tests/test_phirgen.py
=> fix(phirgen): don't rely on `args` when `qubits` carries correct info

.pre-commit-config.yaml, pyproject.toml, pytket/phir/phirgen.py, requirements.txt, tests/test_parallelization.py, tests/test_phirgen.py, tests/test_wasm.py
- pyket API for arguments is quite fragile, we needed to eliminate bits used in the condition  to extract the correct bits used in the WASM function.
- I had unknowingly removed the Conditional case in #152, it was needed for WASM conditional handling in comments.
Fixes #156
=> fix(wasm): correct arguments for conditional wasm functions

pytket/phir/phirgen_parallel.py
Do not display a "No transport duration assigned to gate type 'Init'" warning, it is unnecessary.
=> do nothing on Init gate instead of warning

.pre-commit-config.yaml, pytket/phir/phirgen.py, pytket/phir/phirgen_parallel.py, pytket/phir/sharding/shards2ops.py, requirements.txt, tests/test_phirgen.py
=> feat(phirgen): add support for ZERO/ONE nullary ops

pytket/phir/phirgen.py
See also https://github.com/CQCL/tket/pull/1456 .
Fixes #165 .
=> Set maximum bit width for classical operations according to pytket support

pyproject.toml, pytket/phir/api.py, pytket/phir/cli.py, pytket/phir/phirgen.py, requirements.txt, tests/test_phirgen.py, tests/test_utils.py, tests/test_wasm.py
Makes pytket-phir compatible with pytket version 1.30.0 while maintaining backward compatibility.
Fixes: #203
=> fix: Abstract WORDSIZE to specify maxwidth on qasm conversion

.pre-commit-config.yaml, pytket/phir/api.py, pytket/phir/rebasing/rebaser.py, requirements.txt, tests/test_parallelization.py, tests/test_wasm.py
`ruff` [pointed out](https://github.com/CQCL/pytket-phir/actions/runs/10517561194/job/29141900659) errors like the following:
```
pytket/phir/api.py:94:25: SIM115 Use a context manager for opening files
|
92 |     if wasm_bytes:
93 |         try:
94 |             qasm_file = NamedTemporaryFile(suffix=".qasm", delete=False)
|                         ^^^^^^^^^^^^^^^^^^ SIM115
95 |             wasm_file = NamedTemporaryFile(suffix=".wasm", delete=False)
96 |             qasm_file.write(qasm.encode())
|
```
Turns out resolving these also fixes #108.
Additionally:
- fixes warning "DeprecationWarning: The `auto_rebase_pass()` method is deprecated and will be removed after pytket 1.33, please use `AutoRebase` instead."
- update deps
=> fix: Use a context manager for opening files

pyproject.toml, pytket/phir/phirgen.py, requirements.txt, tests/test_phirgen.py
=> fix: Emit nested binary expressions for classical ops

.pre-commit-config.yaml, CHANGELOG.md, pytket/phir/api.py, pytket/phir/phirgen.py, pytket/phir/phirgen_parallel.py, tests/e2e_test.py, tests/test_phirgen.py, tests/test_utils.py, tests/test_wasm.py
Fixes #237
Also refactor `get_decls` to use the info from pytket `Circuit`.
=> fix: Ensure unused classical registers are not omitted

.pre-commit-config.yaml, pyproject.toml, pytket/phir/phirgen.py, requirements.txt, tests/test_wasm.py
Remove use of unnecessary `NamedTemporaryFile` as pytket>=1.34 allows supports `WasmModuleHandler` that does not require a file interface.
=> refactor: use WasmModuleHandler API to avoid temp files

pyproject.toml
After pytket 2.0 is released we should be able to change to "pytket>=2.0.0" and remove the handling of, and tests involving, `ClassicalExpBox` in this repo.
=> Constrain to pytket 1.x.
